export const SIGNUP_LOADING = 'SING_UP_LOADING';
export const SIGNUP_ERROR = 'SING_UP_ERROR';
export const SIGNUP_SUCCESS = 'SING_UP_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
